version: "3"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=API
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=kinglion
  redis:
    image: redis:alpine
  celery:
    restart: always
    build:
      context: .
    command: celery -A projectapi worker -l info
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      